# Generated by Django 4.1 on 2022-08-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("animal", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("weight", models.DecimalField(decimal_places=3, max_digits=3)),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("Macho", "Macho"),
                            ("Fêmea", "Fêmea"),
                            ("Não Informado", "Not Informed"),
                        ],
                        default="Não Informado",
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
