# Generated by Django 4.1 on 2022-08-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="weight",
            field=models.FloatField(),
        ),
    ]
